name: Test Symbol Table 

on:
  push:
    paths:
      - '**/symbol-table/*'
  pull_request:
    paths:
      - '**/symbol-table/*'

permissions:
  contents: read

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Test symbol-list
      run: |
        cd src/symbol-table/symbol-list/
        gcc test.c symbol-table.c ../stack/stack.c ../list/list.c symbol-list/symbol-list.c -o test
        ./test
