name: Test Utils 

on:
  push:
    paths:
      - '**/utils/*'
  pull_request:
    paths:
      - '**/utils/*'

permissions:
  contents: read

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Test utils
      run: |
        make utils 
        ./utils
