name: Test Stack 

on:
  push:
    paths:
      - '**/stack/*'
  pull_request:
    paths:
      - '**/stack/*'

permissions:
  contents: read

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Test stack
      run: |
        cd src/stack/
        gcc test.c stack.c ../list/list.c -o test
        ./test

