name: test

on:
  push:
  pull_request:

jobs:
  compile:
    runs-on: ubuntu-latest
    steps:
      -
        name: Checkout
        uses: actions/checkout@v2
      -
        name: Install tools
        run: |
         apt-get install -y flex
         apt-get install -y bison
      -
        name: Compile
        run: sh run-tests.sh
