name: Test Symbol 

on:
  push:
    paths:
      - '**/symbol-list/*'
  pull_request:
    paths:
      - '**/symbol-list/*'

permissions:
  contents: read

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Test symbol-list
      run: |
        cd src/symbol-table/symbol-list/
        gcc test.c symbol-list.c ../symbol/symbol.c ../../list/list.c -o test
        ./test
