name: Test Compilation

on:
  push:
  pull_request:

jobs:
  compile:
    runs-on: ubuntu-latest
    steps:
      -
        name: Checkout
        uses: actions/checkout@v2
      -
        name: Install tools
        run: |
         sudo apt-get install -y flex
         sudo apt-get install -y bison
         sudo apt-get intall -y python3-pip
         sudo pip3 install pytest
         sudo pip3 install parametrize_from_file
      -
        name: Test
        run: make test
