name: Test Compilation

on:
  push:
  pull_request:

jobs:
  compile:
    runs-on: ubuntu-latest
    steps:
      -
        name: Checkout
        uses: actions/checkout@v2
      -
        name: Install tools
        run: |
         sudo apt-get install -y flex
         sudo apt-get install -y bison
      -
        name: Compile
        run: bash run-tests.sh
